#!/usr/bin/env perl

use strict;
use warnings;
use v5.16;

=head1 NAME

kicky-sender-mail - sends out emails

=cut

use Kicky;
use AnyEvent;
use Daemon::Generic;
our $VERSION = Kicky->VERSION;

sub gd_preconfig {
    my $self = shift;
    return %{ $self->{config} = Kicky->load_config_file( $self->{configfile} ) || {} }; 
}

sub gd_run {
    my $self = shift;
    my $app = Kicky->new( config => $self->{config} ); 
    my $cv = AnyEvent->condvar;
    $app->sender( platform => 'mail' )->setup_listener;
    $cv->recv;
}

newdaemon(
    progname => 'kicky-sender-mail',
    configfile => 'etc/config.json',
    pidfile => '/tmp/kicky-sender-mail.pid',
);

