#!/usr/bin/env perl

use strict;
use warnings;
use v5.16;

use Getopt::Long;
my %opt = ();
GetOptions (\%opt, 'config|c=s');

use Kicky;
my $app = Kicky->new( config_file => $opt{config} );

use Async::ContextSwitcher qw(context cb_w_context);
$app->rabbit->then(cb_w_context { shift->setup });
exit;
